-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 28, 2022 at 09:54 AM
-- Server version: 10.4.22-MariaDB
-- PHP Version: 8.1.1

-- If you are running MySQL sever in a PC windows,
-- Use lower_case_table_names=0 on Unix (default) and 
-- lower_case_table_names=2 on Windows. This preserves 
-- the lettercase of database and table names.
-- Otherwise, you might have problem by running
-- JPQL queries generated by JPA.
-- See
-- https://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html
 
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


--
-- Database: `mdb_mygreenwichId`
--
-- CREATE DATABASE IF NOT EXISTS `mdb_mygreenwichId` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE `mdb_mygreenwichId`;
-- 
-- --------------------------------------------------------

--
-- Clean every table present
-- DROP and TRUNCATE will note work if foreign_key_checks is 1
-- (no matter if CASCADE is set)
--
SET foreign_key_checks = 0 ;
DROP TABLE IF EXISTS `StudentAccount`;
DROP TABLE IF EXISTS `Student`;
SET foreign_key_checks = 1 ;


--
-- Table structure for table `Student`
--


CREATE TABLE `Student` (
  `Id` int(11) NOT NULL,
  `Name` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `PostalAddress` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Email` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Telephone` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


--
-- Table structure for table `StudentAccount`
--


CREATE TABLE `StudentAccount` (
  `Id` int(11) NOT NULL,
  `studentId` int(11) NOT NULL,
  `Alias` varchar(10000) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Balance` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;









--
-- Indexes for dumped tables
--


--
-- Indexes for table `Student`
--
 
ALTER TABLE `Student`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `StudentAccount`
--
  
ALTER TABLE `StudentAccount`
  ADD PRIMARY KEY (`Id`),
  ADD KEY `studentId` (`studentId`);

--
-- AUTO_INCREMENT for dumped tables
--


--
-- AUTO_INCREMENT for table `Student`
--
ALTER TABLE `Student`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;
  
--
-- AUTO_INCREMENT for table `StudentAccount`
--
ALTER TABLE `StudentAccount`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;



--
-- Constraints for dumped tables
--
--
-- RELATIONSHIPS FOR TABLE `Student`:
--

--
-- Constraints for table `StudentAccount`
--
--
-- RELATIONSHIPS FOR TABLE `StudentAccount`:
--   `studentId`
--       `Student` -> `Id`
--
ALTER TABLE `StudentAccount`
  ADD CONSTRAINT `studentaccount_ibfk_1` FOREIGN KEY (`studentId`) REFERENCES `Student` (`Id`) ON DELETE CASCADE;



-- Dumping data  (only when FOREIGN KEYS are set)
--


--
-- Dumping data for table `Student`
--

INSERT INTO `Student` (`Id`, `Name`,`PostalAddress`,`Email`,`Telephone`) VALUES
(1, 'Student 1','PostalAddress 1','email1@gre.ac.uk','171 565-2221'),
(2, 'Student 2','PostalAddress 2','email2@gre.ac.uk','171 565-2222'),
(3, 'Student 3','PostalAddress 3','email3@gre.ac.uk','171 565-2223'),
(4, 'Student 4','PostalAddress 4','email4@gre.ac.uk','171 565-2224'),
(5, 'Student 5','PostalAddress 5','email5@gre.ac.uk','171 565-2225'),
(6, 'Student 6','PostalAddress 6','email6@gre.ac.uk','171 565-2226'),
(7, 'Student 7','PostalAddress 7','email7@gre.ac.uk','171 565-2227'),
(8, 'Student 8','PostalAddress 8','email8@gre.ac.uk','171 565-2228'),
(9, 'Student 9','PostalAddress 9','email9@gre.ac.uk','171 565-2229'),
(10, 'Student 10','PostalAddress 10','email10@gre.ac.uk','171 565-22210'),
(11, 'Student 11','PostalAddress 11','email11@gre.ac.uk','171 565-22211');

-- --------------------------------------------------------


-- --------------------------------------------------------


-- Dumping data for table `StudentAccount`
--

INSERT INTO `StudentAccount` (`Id`, `studentId`, `Alias`,`Balance`) VALUES
(1, 3, 'Alias1-3',1),
(2, 3, 'Alias2-3',-302),
(3, 3, 'Alias3-3',353),
(4, 3, 'Alias4-3',4564),
(5, 2, 'Alias5-2',355),
(6, 2, 'Alias6-2',-5356),
(7, 1, 'Alias7-1',357),
(8, 1, 'Alias8-1',-5358),
(9, 1, 'Alias9-1',359),
(10, 1, 'Alias10-1',-5360),
(11, 1, 'Alias11-1',361);

-- --------------------------------------------------------


COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
